# Generated by Django 5.1.4 on 2024-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikinamba_app', '0002_alter_myuser_groups_alter_myuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('wash_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
