# Generated by Django 5.1.4 on 2024-12-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikinamba_app', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
